export const SET_IP_LOCATION = 'SET_IP_LOCATION';
export const SET_VALID_PLACE = 'SET_VALID_PLACE';
export const SET_SELECTED_PLACE = 'SET_SELECTED_PLACE';

// U S E R
export const SET_REGISTERED = 'SET_REGISTERED';
export const SET_SIGNIN = 'SET_SIGNIN';
export const SET_USER = 'SET_USER';